import Foundation

/// A streaming MessagePack input cursor, used by ``MessagePackSerializable``
/// conformances (typically generated by the `@MessagePackSerializable` macro)
/// to read values.
///
/// The reader walks a borrowed raw byte buffer; it never copies the input.
/// Each `read` method consumes one value and throws
/// ``MessagePackError/typeMismatch(expected:format:)`` if the next value on
/// the wire has a different type, leaving the reader positioned at that value.
public struct MessagePackReader {
    @usableFromInline
    var parser: MessagePackSerializer.Parser

    /// Creates a reader over `buffer`, which must stay valid while the
    /// reader is used.
    @usableFromInline
    init(buffer: UnsafeRawBufferPointer) {
        self.parser = MessagePackSerializer.Parser(buffer: buffer)
    }

    /// True when every input byte has been consumed.
    @inlinable
    public var isAtEnd: Bool {
        parser.offset == parser.count
    }

    // MARK: Scalars

    /// Consumes a nil marker if the next value is nil, and returns whether it
    /// did. Used to decode optionals.
    @inlinable
    public mutating func readNilIfPresent() -> Bool {
        if parser.offset < parser.count, let base = parser.base,
            base.load(fromByteOffset: parser.offset, as: UInt8.self) == 0xc0
        {
            parser.offset += 1
            return true
        }
        return false
    }

    @inlinable
    public mutating func readBool() throws(MessagePackError) -> Bool {
        guard let value = try parser.readRawBool() else {
            throw MessagePackError.typeMismatch(expected: "bool", format: try parser.peekFormat())
        }
        return value
    }

    /// Reads any integer format into `T`, throwing
    /// ``MessagePackError/integerOverflow`` if the value does not fit.
    @inlinable
    public mutating func readInteger<T: FixedWidthInteger>(
        _ type: T.Type = T.self
    ) throws(MessagePackError) -> T {
        guard let raw = try parser.readRawInteger() else {
            throw MessagePackError.typeMismatch(
                expected: "integer", format: try parser.peekFormat())
        }
        switch raw {
        case .signed(let value):
            guard let converted = T(exactly: value) else {
                throw MessagePackError.integerOverflow
            }
            return converted
        case .unsigned(let value):
            guard let converted = T(exactly: value) else {
                throw MessagePackError.integerOverflow
            }
            return converted
        }
    }

    /// Reads a float 32/64 (or, leniently, any integer) as a `Double`.
    @inlinable
    public mutating func readDouble() throws(MessagePackError) -> Double {
        guard let value = try parser.readRawDouble() else {
            throw MessagePackError.typeMismatch(expected: "float", format: try parser.peekFormat())
        }
        return value
    }

    /// Reads a float 32/64 (or, leniently, any integer) as a `Float`.
    /// float 64 values are rounded to the nearest `Float`.
    @inlinable
    public mutating func readFloat() throws(MessagePackError) -> Float {
        Float(try readDouble())
    }

    @inlinable
    public mutating func readString() throws(MessagePackError) -> String {
        guard let value = try parser.readRawString() else {
            throw MessagePackError.typeMismatch(expected: "string", format: try parser.peekFormat())
        }
        return value
    }

    /// Reads a binary (bin 8/16/32) payload.
    @inlinable
    public mutating func readBinary() throws(MessagePackError) -> Data {
        guard let value = try parser.readRawBinary() else {
            throw MessagePackError.typeMismatch(expected: "binary", format: try parser.peekFormat())
        }
        return value
    }

    // MARK: Containers and extensions

    /// Reads an array header and returns the element count. The count is
    /// validated against the remaining input (each element takes at least one
    /// byte), so it is safe to reserve capacity for.
    @inlinable
    public mutating func readArrayHeader() throws(MessagePackError) -> Int {
        guard let count = try parser.readArrayHeader() else {
            throw MessagePackError.typeMismatch(expected: "array", format: try parser.peekFormat())
        }
        guard count <= parser.count - parser.offset else {
            throw MessagePackError.insufficientData
        }
        return count
    }

    /// Reads a map header and returns the entry count. The count is validated
    /// against the remaining input (each entry takes at least two bytes), so
    /// it is safe to reserve capacity for.
    @inlinable
    public mutating func readMapHeader() throws(MessagePackError) -> Int {
        guard let count = try parser.readMapHeader() else {
            throw MessagePackError.typeMismatch(expected: "map", format: try parser.peekFormat())
        }
        guard count <= (parser.count - parser.offset) / 2 else {
            throw MessagePackError.insufficientData
        }
        return count
    }

    /// Reads an extension value (type code and payload).
    @inlinable
    public mutating func readExt() throws(MessagePackError) -> (type: Int8, data: Data) {
        guard let value = try parser.readRawExt() else {
            throw MessagePackError.typeMismatch(expected: "ext", format: try parser.peekFormat())
        }
        return value
    }

    /// Reads a timestamp (ext type -1).
    @inlinable
    public mutating func readTimestamp() throws(MessagePackError) -> MessagePackTimestamp {
        let (type, data) = try readExt()
        guard let timestamp = MessagePackTimestamp(extType: type, data: data) else {
            throw MessagePackError.invalidTimestamp
        }
        return timestamp
    }

    /// Skips one complete value (including nested containers).
    @inlinable
    public mutating func skipValue() throws(MessagePackError) {
        try parser.skipValue()
    }

    /// Reads a whole value tree as a ``MessagePackValue``. Nesting beyond
    /// ``MessagePackSerializer``'s depth limit throws
    /// ``MessagePackError/depthLimitExceeded``.
    public mutating func readValue() throws(MessagePackError) -> MessagePackValue {
        try parser.parseValue()
    }
}
