import Foundation

/// A type with a direct, statically generated MessagePack representation.
///
/// Conformances are usually generated by the `@MessagePackSerializable`
/// macro, which serializes a struct as a map of field name to field value:
///
/// ```swift
/// @MessagePackSerializable
/// struct Foo {
///     let bar: Int
///     let hoge: String
/// }
///
/// let data = MessagePackSerializer.serialize(Foo(bar: 0, hoge: ""))
/// let foo = try MessagePackSerializer.deserialize(Foo.self, from: data)
/// ```
///
/// Unlike `Codable` with ``MessagePackEncoder``/``MessagePackDecoder``, this
/// path has no dynamic container machinery: the generated code writes and
/// reads the wire format directly, which makes it considerably faster. The
/// bytes produced are identical to what the `Codable` path produces for an
/// equivalent type.
///
/// Enums with a raw value don't need the macro: declaring the conformance is
/// enough, because a default implementation is provided for
/// `RawRepresentable` types whose `RawValue` conforms.
public protocol MessagePackSerializable {
    /// Writes the MessagePack representation of `self` to `writer`.
    func serialize(into writer: inout MessagePackWriter)

    /// Reads a value from `reader`, consuming exactly one MessagePack value.
    init(messagePack reader: inout MessagePackReader) throws(MessagePackError)
}

/// Generates a ``MessagePackSerializable`` conformance for a struct.
///
/// The struct is serialized as a MessagePack map with one entry per stored
/// property, keyed by property name, in declaration order. Deserialization
/// accepts fields in any order, skips unknown keys, throws
/// ``MessagePackError/missingField(_:)`` for absent non-optional fields
/// without a default value, and uses the property's default value (or `nil`
/// for optionals) when a field is absent.
///
/// - `@MessagePackKey("name")` overrides the map key for a property.
/// - `@MessagePackIgnored` excludes a stored property entirely; it must have
///   a default value (or be an optional `var`) so the generated initializer
///   compiles.
/// - Computed, `static`, and `lazy` properties are ignored. `let` properties
///   with a default value are serialized but not deserialized (they cannot
///   be assigned), matching `Codable` synthesis.
@attached(extension, conformances: MessagePackSerializable, names: named(serialize), named(init))
public macro MessagePackSerializable() =
    #externalMacro(module: "MessagePackSwiftMacros", type: "MessagePackSerializableMacro")

/// Excludes a stored property from `@MessagePackSerializable` serialization.
@attached(peer)
public macro MessagePackIgnored() =
    #externalMacro(module: "MessagePackSwiftMacros", type: "MessagePackIgnoredMacro")

/// Overrides the map key `@MessagePackSerializable` uses for a stored
/// property.
@attached(peer)
public macro MessagePackKey(_ key: StaticString) =
    #externalMacro(module: "MessagePackSwiftMacros", type: "MessagePackKeyMacro")

// MARK: - Serializer entry points

extension MessagePackSerializer {
    /// Serializes a ``MessagePackSerializable`` value into MessagePack binary
    /// data.
    ///
    /// Values whose lengths exceed the MessagePack limits (strings, binary,
    /// or containers beyond 2^32-1 bytes/elements), and dates outside the
    /// timestamp range, stop execution with a precondition failure.
    @inlinable
    public static func serialize<T: MessagePackSerializable>(_ value: T) -> Data {
        var writer = MessagePackWriter(initialCapacity: 1024)
        value.serialize(into: &writer)
        return writer.finish()
    }

    /// Deserializes MessagePack binary data into a ``MessagePackSerializable``
    /// value.
    ///
    /// Throws ``MessagePackError/trailingBytes`` if `data` contains bytes
    /// beyond the first top-level value.
    @inlinable
    public static func deserialize<T: MessagePackSerializable>(
        _ type: T.Type = T.self, from data: Data
    ) throws(MessagePackError) -> T {
        let result: Result<T, MessagePackError> = data.withUnsafeBytes { buffer in
            var reader = MessagePackReader(buffer: buffer)
            do throws(MessagePackError) {
                let value = try T(messagePack: &reader)
                guard reader.isAtEnd else {
                    throw MessagePackError.trailingBytes
                }
                return .success(value)
            } catch {
                return .failure(error)
            }
        }
        return try result.get()
    }
}

// MARK: - RawRepresentable default implementation

extension MessagePackSerializable where Self: RawRepresentable, RawValue: MessagePackSerializable {
    /// Serializes the raw value.
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) {
        rawValue.serialize(into: &writer)
    }

    /// Deserializes a raw value and converts it, throwing
    /// ``MessagePackError/invalidRawValue`` when no case matches.
    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        let rawValue = try RawValue(messagePack: &reader)
        guard let value = Self(rawValue: rawValue) else {
            throw MessagePackError.invalidRawValue
        }
        self = value
    }
}

// MARK: - Standard library conformances

extension Bool: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readBool()
    }
}

extension Int: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readInteger()
    }
}

extension Int8: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readInteger()
    }
}

extension Int16: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readInteger()
    }
}

extension Int32: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readInteger()
    }
}

extension Int64: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readInteger()
    }
}

extension UInt: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readInteger()
    }
}

extension UInt8: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readInteger()
    }
}

extension UInt16: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readInteger()
    }
}

extension UInt32: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readInteger()
    }
}

extension UInt64: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readInteger()
    }
}

extension Float: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readFloat()
    }
}

extension Double: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readDouble()
    }
}

extension String: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readString()
    }
}

extension Optional: MessagePackSerializable where Wrapped: MessagePackSerializable {
    /// Serializes the wrapped value, or MessagePack nil for `nil`.
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) {
        if let value = self {
            value.serialize(into: &writer)
        } else {
            writer.writeNil()
        }
    }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        if reader.readNilIfPresent() {
            self = nil
        } else {
            self = .some(try Wrapped(messagePack: &reader))
        }
    }
}

extension Array: MessagePackSerializable where Element: MessagePackSerializable {
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) {
        writer.writeArrayHeader(count: count)
        for element in self {
            element.serialize(into: &writer)
        }
    }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        let count = try reader.readArrayHeader()
        self.init()
        reserveCapacity(count)
        for _ in 0..<count {
            append(try Element(messagePack: &reader))
        }
    }
}

extension Set: MessagePackSerializable where Element: MessagePackSerializable {
    /// Serialized as a MessagePack array. Element order is unspecified.
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) {
        writer.writeArrayHeader(count: count)
        for element in self {
            element.serialize(into: &writer)
        }
    }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        let count = try reader.readArrayHeader()
        self.init(minimumCapacity: count)
        for _ in 0..<count {
            insert(try Element(messagePack: &reader))
        }
    }
}

extension Dictionary: MessagePackSerializable
where Key: MessagePackSerializable, Value: MessagePackSerializable {
    /// Serialized as a MessagePack map. Entry order is unspecified.
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) {
        writer.writeMapHeader(count: count)
        for (key, value) in self {
            key.serialize(into: &writer)
            value.serialize(into: &writer)
        }
    }

    /// Duplicate keys on the wire are accepted; the last value wins.
    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        let count = try reader.readMapHeader()
        self.init(minimumCapacity: count)
        for _ in 0..<count {
            let key = try Key(messagePack: &reader)
            self[key] = try Value(messagePack: &reader)
        }
    }
}

// MARK: - Foundation and MessagePack type conformances

extension Data: MessagePackSerializable {
    /// Serialized as MessagePack binary (bin 8/16/32).
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readBinary()
    }
}

extension Date: MessagePackSerializable {
    /// Serialized as the timestamp extension type (-1), rounded to nanosecond
    /// precision. Dates outside the timestamp range (or with a non-finite
    /// interval) stop execution with a precondition failure; represent such
    /// values some other way before serializing.
    public func serialize(into writer: inout MessagePackWriter) {
        writer.write(MessagePackTimestamp(date: self))
    }

    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readTimestamp().date
    }
}

extension MessagePackTimestamp: MessagePackSerializable {
    /// Serialized as the timestamp extension type (-1).
    @inlinable
    public func serialize(into writer: inout MessagePackWriter) { writer.write(self) }

    @inlinable
    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readTimestamp()
    }
}

extension MessagePackValue: MessagePackSerializable {
    /// Serializes the value tree, allowing dynamically shaped fields inside
    /// `@MessagePackSerializable` types.
    public func serialize(into writer: inout MessagePackWriter) {
        writer.write(self)
    }

    public init(messagePack reader: inout MessagePackReader) throws(MessagePackError) {
        self = try reader.readValue()
    }
}
